use_frameworks! :linkage => :static
abstract_target 'CommonPods' do
  target 'TrustTunnelClient-iOS' do
    platform :ios, '14.0'
    pod 'TOMLDecoder'
  end
  target 'TrustTunnelClient-MacOS' do
    platform :osx, '10.15'
    pod 'TOMLDecoder'
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Set the minimum deployment target for every pod.
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.15'
    end
  end
end

workspace 'TrustTunnelClient.xcworkspace'
