name: 🐞 Bug report
description: Report a bug related to TrustTunnel console client
title: "[Bug]: "
labels: ["Bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

        ⚠️ Please note:
        - This template is intended for **bugs only**
        - Questions and usage issues should go to Discussions
        - Issues that do not follow this template may be closed

  - type: checkboxes
    attributes:
      label: Before submitting, please confirm
      options:
        - label: I read the README and followed all setup steps in order
          required: true
        - label: I searched existing issues and found no duplicates
          required: true
        - label: I am using the latest version of the TrustTunnel console client
          required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment details
      description: |
        Please provide relevant environment details.
        Examples:
          - **OS**: Ubuntu v22.04
          - **Architecture**: x86-64
      value: |
        - OS:
        - Architecture:
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: App version
      description: Version where the issue occurs
      placeholder: ex. 0.99.99
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        Provide clear and minimal steps to reproduce the issue.
        If possible, include a minimal reproducible example.
      placeholder: |
        1. Run the app
        2. Click on the toggle button
        3. Observe crash / incorrect behavior
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: Describe what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      placeholder: Describe what actually happened.
    validations:
      required: true

  - type: textarea
    id: screens
    attributes:
      label: Screenshots
      description: |
        If applicable add screenshots explaining your problem.
        You can drag and drop images or paste them from clipboard.
        Use `<details> </details>` tag to hide screenshots under the spoiler.
      placeholder: If applicable add screenshots explaining your problem.
      value: |
          <details><summary>Screenshot 1</summary>

          <!-- paste screenshot here -->

          </details>
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      placeholder: Add any other context about the problem here.
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ---

        Upvote [important issues](https://github.com/TrustTunnel/TrustTunnelClient/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+) with a :+1:
