---
version: 2
triggers: [ ]

plan:
  project-key: CL
  key: TTCLI
  name: TrustTunnelClient - Deploy

stages:
  - Build artifacts:
      manual: false
      final: false
      jobs:
        - Linux build
        - Mac build
        - Win build
  - Deploy artifacts:
      manual: false
      final: false
      jobs:
        - Deploy artifacts

Linux build:
  key: BL
  docker:
    image: adguard/core-libs:2.8
    volumes:
      ${bamboo.working.directory}: ${bamboo.working.directory}
      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
      ${bamboo.git.cache.directory}: ${bamboo.git.cache.directory}
      ${system.HOME}/.ssh: /root/.ssh
    docker-run-arguments: [ ]
  tasks:
    - !include docker-clean.yaml
    - checkout:
        description: Checkout Default Repository
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash
            set -x -e

            conan remote add --index 0 art ${bamboo_conanRepoUrl} || true
            VPNLIBS_ROOT=${PWD}
            mkdir -p artifacts
            ARTIFACTS_DIR=${VPNLIBS_ROOT}/artifacts

            VERSION=$(cat conandata.yml | grep "[0-9]*\.[0-9]*." | tail -1 | sed "s/\"//" | sed "s/\"\://" | sed "s/ //g")

            ARCHES=${ARCHES:-x86_64 aarch64 armv7 mips mipsel}

            # Set up GPG for signing binaries
            GPG_KEY=devteam@adguard.com
            echo "${bamboo.gpgSecretKeyPart1}${bamboo.gpgSecretKeyPart2}"\
                        | awk '{ gsub(/\\n/, "\n"); print; }'\
                        | gpg --import --batch --yes

            rustup +nightly component add rust-src

            for ARCH in $ARCHES; do
              mkdir -p build_${ARCH}
              SYSTEM_PROCESSOR=${ARCH}
              EABI=
              SF=
              case ${ARCH} in
                armv7)
                EABI=eabi
                ;;
                mips)
                SF=sf
                ;;
                mipsel)
                SF=sf
              esac

              # Rust adds -lunwind when statically linking even when there's no backtrace code, and GCC has backtrace implementation in other library
              p="$(${ARCH}-linux-musl${EABI}${SF}-gcc -print-file-name=libgcc_eh.a)" && [ "$p" != "libgcc_eh.a" ] && ln -sf "$(basename "$p")" "$(dirname "$p")/libunwind.a"

              cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja \
                -DCMAKE_C_COMPILER=${ARCH}-linux-musl${EABI}${SF}-gcc \
                -DCMAKE_CXX_COMPILER=${ARCH}-linux-musl${EABI}${SF}-g++ \
                -DCMAKE_SYSTEM_PROCESSOR=${SYSTEM_PROCESSOR} \
                -DCMAKE_SYSTEM_NAME=Linux \
                -DCMAKE_CROSSCOMPILING=ON \
              -S ${VPNLIBS_ROOT} \
              -B build_${ARCH}
              cmake --build build_${ARCH} --target trusttunnel_client
              cmake --build build_${ARCH} --target setup_wizard
              NAME=trusttunnel_client-v${VERSION}-linux-${ARCH}
              pushd build_${ARCH}/trusttunnel
                llvm-strip trusttunnel_client
                llvm-strip setup_wizard
                # Sign binaries with GPG
                gpg --default-key "${GPG_KEY}" \
                    --detach-sig \
                    --passphrase "${bamboo.gpgPassword}" \
                    --pinentry-mode loopback \
                    trusttunnel_client
                gpg --default-key "${GPG_KEY}" \
                    --detach-sig \
                    --passphrase "${bamboo.gpgPassword}" \
                    --pinentry-mode loopback \
                    setup_wizard
                cp ${VPNLIBS_ROOT}/LICENSE .
                # Include .sig files in the archive
                tar zcf ${NAME}.tar.gz --transform "s,^,${NAME}/," trusttunnel_client trusttunnel_client.sig setup_wizard setup_wizard.sig LICENSE
                mv ${NAME}.tar.gz ${ARTIFACTS_DIR}/
              popd
            done
  final-tasks:
    - script:
        file: bamboo-specs/scripts/conan_upload_and_cleanup.sh
        description: Conan upload and cleanup
  requirements:
    - adg-privileged-docker
  artifact-subscriptions: [ ]
  artifacts:
    - name: Build for Linux
      location: artifacts
      pattern: 'trusttunnel_client-*.tar.gz'
      required: true
      shared: true

Mac build:
  key: BM
  tasks:
    - !include docker-clean.yaml
    - checkout:
        description: Checkout Default Repository
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash
            set -x -e

            CODESIGN_IDENTITY="Developer ID Application: Adguard Software Limited (TC3Q7MAJXF)"
            CODESIGN_IDENTIFIER="com.adguard.trusttunnel.client.main"

            python3 -m venv venv
            . venv/bin/activate
            pip install conan

            conan remote add --index 0 art ${bamboo_conanRepoUrl} || true
            printf "%b\n" "${bamboo_sshSecretKey}" | ssh-add -

            bundle config --local path '.bundle/vendor'
            bundle config
            bundle install
            export REPO_ROOT=${PWD}
            bundle exec fastlane remove_certs || true
            bundle exec fastlane certs

            VERSION=$(cat conandata.yml | grep "[0-9]*\.[0-9]*." | tail -1 | sed "s/\"//" | sed "s/\"\://" | sed "s/ //g")
            
            # Set up GPG for signing binaries
            GPG_KEY=devteam@adguard.com
            echo "${bamboo.gpgSecretKeyPart1}${bamboo.gpgSecretKeyPart2}"\
                        | awk '{ gsub(/\\n/, "\n"); print; }'\
                        | gpg --import --batch --yes

            ARCHES=${ARCHES:-x86_64 arm64}
            for ARCH in $ARCHES; do
              mkdir -p build_${ARCH}
              cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja \
              -DCMAKE_C_COMPILER=clang \
              -DCMAKE_CXX_COMPILER=clang++ \
              -DCMAKE_CXX_FLAGS="-stdlib=libc++" \
              -DCMAKE_OSX_ARCHITECTURES=${ARCH} \
              -DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
              -S ${REPO_ROOT} \
              -B build_${ARCH}
              cmake --build build_${ARCH} --target trusttunnel_client
              cmake --build build_${ARCH} --target setup_wizard
            done

            mkdir -p build_universal
            pushd build_universal
              lipo -create -output trusttunnel_client ../build_arm64/trusttunnel/trusttunnel_client ../build_x86_64/trusttunnel/trusttunnel_client
              strip trusttunnel_client
              lipo -create -output setup_wizard ../build_arm64/trusttunnel/setup_wizard ../build_x86_64/trusttunnel/setup_wizard
              strip setup_wizard
              codesign -s "${CODESIGN_IDENTITY}" -i "${CODESIGN_IDENTIFIER}" --options=runtime trusttunnel_client
              codesign -s "${CODESIGN_IDENTITY}" -i "${CODESIGN_IDENTIFIER}" --options=runtime setup_wizard
              BIN_PATH=${PWD}
              pushd ${REPO_ROOT}
                bundle exec fastlane notari id:"${CODESIGN_IDENTIFIER}" bundle:"${BIN_PATH}/trusttunnel_client"
                bundle exec fastlane notari id:"${CODESIGN_IDENTIFIER}" bundle:"${BIN_PATH}/setup_wizard"
                bundle exec fastlane remove_certs || true
              popd
              # Sign binaries with GPG
                gpg --default-key "${GPG_KEY}" \
                    --detach-sig \
                    --passphrase "${bamboo.gpgPassword}" \
                    --pinentry-mode loopback \
                    trusttunnel_client
                gpg --default-key "${GPG_KEY}" \
                    --detach-sig \
                    --passphrase "${bamboo.gpgPassword}" \
                    --pinentry-mode loopback \
                    setup_wizard
              cp ${REPO_ROOT}/LICENSE .
              NAME=trusttunnel_client-v${VERSION}-macos-universal
              # Include .sig files in the archive
              tar zcf ${NAME}.tar.gz -s ",^,${NAME}/," trusttunnel_client trusttunnel_client.sig setup_wizard setup_wizard.sig LICENSE
            popd
    - script:
        scripts:
          - |-
            python3 -m venv venv
            . venv/bin/activate
            pip install conan
            bamboo-specs/scripts/conan_upload_and_cleanup.sh
        description: Conan upload and cleanup
  requirements:
    - ephemeral
    - image: registry.int.agrd.dev/macos/tahoe-build-agent-xcode26.1.1:latest
  artifact-subscriptions: [ ]
  artifacts:
    - name: Build for Mac
      location: build_universal
      pattern: 'trusttunnel_client-*.tar.gz'
      required: true
      shared: true

Win build:
  key: WB
  tasks:
    - checkout:
        description: Checkout Default Repository
        force-clean-build: 'true'
    - script:
        interpreter: WINDOWS_POWER_SHELL
        scripts:
          - |-
            $ErrorActionPreference = 'Stop'

            & conan remote add --index 0 art $Env:bamboo_conanRepoUrl
            $Env:bamboo_sshSecretKey -replace '\\n', "`n" | sc $Env:USERPROFILE\.ssh\id_rsa

            $repoRoot = (Get-Location).Path

            # Save vcvars to switch between them
            $vcvars32 = cmd /c "vcvarsall amd64_x86 & set"
            $vcvars64 = cmd /c "vcvarsall amd64 & set"
            $vcvarsarm64 = cmd /c "vcvarsall amd64_arm64 & set"
            function setvar($_) {
              if ($_ -match "=") {
                $v = $_.split("="); set-item -force -path "ENV:\$($v[0])"  -value "$($v[1])"
              }
            }
            function Sign-File([string]$Path) {
              Write-Host "Signing: $Path"
              & python -m pip install --disable-pip-version-check -q requests
              if (!$?) { throw 'Failed to install Python requests' }
              & python (Join-Path $repoRoot 'scripts\win_sign_binary.py') $Path
              if (!$?) { throw "Signing helper failed for: $Path" }
              Write-Host "Success"
            }

            $versionLine = Get-Content conandata.yml | Select-String -Pattern '[0-9]+\.[0-9]+\.' | Select-Object -Last 1
            if (!$versionLine) { throw 'Failed to detect VERSION from conandata.yml' }
            $VERSION = ($versionLine.ToString() -replace '"', '' -replace ':', '' -replace ' ', '').Trim()

            New-Item -ItemType Directory -Force -Path artifacts | Out-Null

            # This is a copy of https://www.wintun.net/builds/wintun-0.14.1.zip
            $wintunUrl = "https://$Env:bamboo_artifactoryHostname/artifactory/adguard-pods/binaries/wintun-0.14.1.zip"
            $wintunZip = Join-Path $PWD 'wintun-0.14.1.zip'
            Invoke-WebRequest -Uri $wintunUrl -OutFile $wintunZip
            Expand-Archive -Force -Path $wintunZip -DestinationPath 'wintun'

            function Build-And-Package([string]$BuildDir, $VcvarsEnv, [string]$ArchName, [string]$WintunBinSubdir) {
              & {
                $VcvarsEnv | foreach { setvar $_ }
                New-Item -ItemType Directory -Force -Path $BuildDir | Out-Null
                pushd $BuildDir
                & cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo `
                  -DCMAKE_C_COMPILER="cl.exe" `
                  -DCMAKE_CXX_COMPILER="cl.exe" `
                  -G Ninja ..
                if (!$?) { exit 1 }
                & ninja trusttunnel_client setup_wizard
                if (!$?) { exit 1 }
                Sign-File "trusttunnel\\trusttunnel_client.exe"
                Sign-File "trusttunnel\\setup_wizard.exe"
                popd
              }

              $NAME = "trusttunnel_client-v$VERSION-windows-$ArchName"
              Copy-Item -Force LICENSE "$BuildDir\trusttunnel\LICENSE.txt"
              Copy-Item -Force "wintun\wintun\bin\$WintunBinSubdir\wintun.dll" "$BuildDir\trusttunnel\wintun.dll"
              Copy-Item -Force 'wintun\wintun\LICENSE.txt' "$BuildDir\trusttunnel\WINTUN_LICENSE.txt"
              Compress-Archive -Force -DestinationPath ("artifacts\\$NAME.zip") -Path @(
                "$BuildDir\\trusttunnel\\trusttunnel_client.exe",
                "$BuildDir\\trusttunnel\\setup_wizard.exe",
                "$BuildDir\\trusttunnel\\LICENSE.txt",
                "$BuildDir\\trusttunnel\\wintun.dll",
                "$BuildDir\\trusttunnel\\WINTUN_LICENSE.txt"
              )
            }

            Build-And-Package "build64" $vcvars64 "x86_64" "amd64"
            Build-And-Package "build32" $vcvars32 "i686" "x86"
            Build-And-Package "buildarm64" $vcvarsarm64 "aarch64" "arm64"
  requirements:
    - ephemeral-windows
    - image: registry.int.agrd.dev/windows/windows11-bamboo:19
  artifact-subscriptions: [ ]
  artifacts:
    - name: Build for Windows
      location: artifacts
      pattern: 'trusttunnel_client-*.zip'
      required: true
      shared: true

Deploy artifacts:
  key: DA
  docker:
    image: adguard/core-libs:2.8
    volumes:
      ${bamboo.working.directory}: ${bamboo.working.directory}
      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
      ${bamboo.git.cache.directory}: ${bamboo.git.cache.directory}
      ${system.HOME}/.ssh: /root/.ssh
    docker-run-arguments: [ ]
  tasks:
    - clean
    - checkout:
        description: Checkout Default Repository
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash
            set -x -e

            printf "%b\n" "${bamboo_sshSecretKey}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa

            git config user.email "Bamboo"
            git config user.name "Bamboo"

            VERSION=$(cat conandata.yml | grep "[0-9]*\.[0-9]*." | tail -1 | sed "s/\"//" | sed "s/\"\://" | sed "s/ //g")

            # Update version in install script and push tag
            sed -i -e "s/^version='[0-9\.]*'$/version='${VERSION}'/" scripts/install.sh
            git add scripts/install.sh
            git commit -m "skipci: Automatic increment version for install script"
            TAG=v${VERSION}
            git tag -d ${TAG} || true
            git tag ${TAG}
            git remote set-url origin "${bamboo_planRepository_1_repositoryUrl}"
            git push origin HEAD
            git push origin ${TAG}

            git clone https://${bamboo_githubPublicRepoPassword}:@github.com/TrustTunnel/TrustTunnelClient/
            cd TrustTunnelClient
            CHANGELOG_URL="https://github.com/TrustTunnel/TrustTunnelClient/blob/${TAG}/CHANGELOG.md"
            gh config set -h github.com oauth_token "${bamboo_githubPublicRepoPassword}" || exit 1
            gh release delete -y ${TAG} || true
            gh release create ${TAG} -t "${TAG}" -n "See [CHANGELOG.md](${CHANGELOG_URL}) for the list of changes."

            LINUX_ARCHES=${LINUX_ARCHES:-x86_64 aarch64 armv7 mips mipsel}
            for ARCH in $LINUX_ARCHES; do
              gh release upload ${TAG} ../build/linux/trusttunnel_client-v${VERSION}-linux-${ARCH}.tar.gz
            done
            gh release upload ${TAG} ../build/mac/trusttunnel_client-v${VERSION}-macos-universal.tar.gz

            WIN_ARCHES=${WIN_ARCHES:-x86_64 i686 aarch64}
            for ARCH in $WIN_ARCHES; do
              gh release upload ${TAG} ../build/win/trusttunnel_client-v${VERSION}-windows-${ARCH}.zip
            done
  requirements:
    - adg-privileged-docker
  artifact-subscriptions:
    - artifact: Build for Linux
      destination: build/linux
    - artifact: Build for Mac
      destination: build/mac
    - artifact: Build for Windows
      destination: build/win
  artifacts: []


repositories:
  - core-libs/vpn-libs:
      scope: global

branches:
  create: manually
  delete: never
  link-to-jira: true

notifications: [ ]

labels: [ ]

other:
  concurrent-build-plugin: system-default
