---
version: 2
plan:
  project-key: CL
  key: VLIV
  name: VpnLibs - Increment Version
stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Increment version
Increment version:
  key: JOB1
  docker:
    image: adguard/core-libs:2.6
    volumes:
      ${bamboo.working.directory}: ${bamboo.working.directory}
      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
    docker-run-arguments: [ ]
  tasks:
    - !include docker-clean.yaml
    - checkout:
        repository: core-libs/vpn-libs
        path: vpn-libs
    - checkout:
        repository: git-scripts
        path: git-scripts
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x -e

            git config user.name "Bamboo"
            git config user.email "Bamboo"

            if [ ${bamboo_custom_version} = "none" ]; then
                bamboo_custom_version=
            fi
            ./scripts/increment_version.sh ${bamboo_custom_version} || exit 1

            ../git-scripts/git_kit.sh pull ${bamboo_planRepository_repositoryUrl}
            git reset
            git add conandata.yml
            git add CHANGELOG.md
            git add platform/android/lib/build.gradle.kts
            git commit -m "skipci: Automatic version increment by Bamboo"
            git push

            case "${bamboo_repository_branch_name}" in
            master)
                BAMBOO_URL=$(echo ${bamboo_resultsUrl} | sed -ne 's|\(https://[^/]\+\)/.*|\1|p')
                curl -H "Authorization: Bearer ${bamboo.bambooTriggerTokenSecret}" \
                    "${BAMBOO_URL}/rest/api/latest/queue/CL-VUCRP" -X POST -d "executeAllStages=1"
                ;;
            esac
        working-dir: vpn-libs
        description: Increment version
  requirements:
    - adg-privileged-docker
  artifact-subscriptions: [ ]
variables:
  custom.version: 'none'
repositories:
  - core-libs/vpn-libs:
      scope: global
  - git-scripts
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications: [ ]
labels: [ ]
other:
  concurrent-build-plugin: system-default
