---
version: 2

plan:
  project-key: CL
  key: VLRUT
  name: VpnLibs - Run Live Unit Tests

stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Run live unit tests

Run live unit tests:
  key: RLUT
  description: Runs C++ live unit tests on schedule
  docker:
    image: adguard/core-libs:2.8
    volumes:
      ${bamboo.working.directory}: ${bamboo.working.directory}
      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
      ${system.HOME}/.ssh: /root/.ssh
    docker-run-arguments: [ ]
  tasks:
    - !include docker-clean.yaml
    - checkout:
        repository: core-libs/vpn-libs
        path: vpn-libs
        force-clean-build: 'true'
        description: Checkout client
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x -e

            python3 -m pip install conan --upgrade

            conan remote add --index 0 art ${bamboo.conanRepoUrl} || true

            SRC_ROOT=${PWD}
            mkdir -p /build_no_asan && cd /build_no_asan

            export LDFLAGS=-fuse-ld=lld
            cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
              -DCMAKE_C_COMPILER=clang \
              -DCMAKE_CXX_COMPILER=clang++ \
              -DVPNLIBS_ENABLE_LIVE_TESTS=ON \
              -DCMAKE_CXX_FLAGS='-stdlib=libc++' \
              ${SRC_ROOT}

            make -j 4 live_tests
            cd /build_no_asan
            ctest --output-on-failure -L live -E test_vpn_client_live
        description: Build and run vpn-libs live unit tests
        working-dir: vpn-libs
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash
            conan remote login art "${bamboo_artifactoryUser}" --password "${bamboo_artifactoryPassword}" > upload.txt 2>&1
            conan upload -r art -c "*" >> upload.txt 2>&1
            echo conan upload finished with status $?
            conan remove -c "*"
        description: Conan upload and cleanup
  requirements:
    - adg-privileged-docker
  artifact-subscriptions: [ ]

repositories:
  - core-libs/vpn-libs:
      scope: global

triggers:
  - cron:
      expression: 0 0 9 ? * *

branches:
  create: manually
  delete: never
  link-to-jira: true

notifications:
  - events:
      - plan-failed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-libs
  - events:
      - plan-completed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-libs-vcs

labels: [ ]

other:
  concurrent-build-plugin: system-default
