---
version: 2
plan:
  project-key: CL
  key: VLRIT
  name: VpnLibs - Run Browser Integrated Test
stages:
  - Build stage:
      manual: false
      final: false
      jobs:
        - Build binaries
  - Tests stage:
      manual: false
      final: false
      jobs:
        - Run integration test
Build binaries:
  key: BB
  description: Build client and endpoint binaries
  docker:
    image: adguard/core-libs:2.6
  tasks:
    - !include docker-clean.yaml
    - checkout:
        repository: core-libs/vpn-libs
        path: vpn-libs
        force-clean-build: 'true'
        description: Checkout client
    - checkout:
        repository: core-libs/vpn-libs-endpoint
        path: vpn-libs-endpoint
        force-clean-build: 'true'
        description: Checkout endpoint
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash

            set -x -e

            pwd
            ls -l
            mkdir -p output
            export OUTPUT_DIR=${PWD}/output
            export SOURCE_DIR=${PWD}

            export CONAN_REPO_URL=${bamboo.conanRepoUrl}
            vpn-libs/integration-tests/build_client.sh
            vpn-libs/integration-tests/build_endpoint.sh
  requirements:
    - adg-privileged-docker
  artifacts:
    - name: standalone_client
      location: output
      pattern: standalone_client
      shared: true
    - name: vpn_endpoint
      location: output
      pattern: vpn_endpoint
      shared: true
  artifact-subscriptions: [ ]
Run integration test:
  key: JOB1
  description: Runs integration test
  docker:
    image: adguard/core-libs-testing:2.6.0
    docker-run-arguments: [ --privileged, --device=/dev/net/tun ]
  artifact-subscriptions:
    - artifact: standalone_client
      destination: output
    - artifact: vpn_endpoint
      destination: output
  tasks:
    - !include docker-clean.yaml
    - checkout:
        repository: core-libs/vpn-libs
        path: vpn-libs
        force-clean-build: 'true'
        description: Checkout client
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash

            set -x -e

            export OUTPUT_DIR=${PWD}/output
            export TEST_DIR=${PWD}/vpn-libs/integration-tests/tests

            # Nameserver with global routable IP is required here.
            # 94.140.14.140 is AdGuard Unfiltered DNS
            echo nameserver 94.140.14.140 > /etc/resolv.conf

            # Download agvpn_helper from artifactory
            curl -O https://art.int.agrd.dev/artifactory/adguard-pods/binaries/agvpn_helper/agvpn_helper-linux.tar.gz
            tar -C ${OUTPUT_DIR} -xvf agvpn_helper-linux.tar.gz

            ${TEST_DIR}/browser/run.sh ${bamboo.vpnLibsAppId} ${bamboo.vpnLibsTokenSecret}
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash

            set -x

            pushd output

            # Check that file exists and is not empty
            if [ ! -f vpn_tun_http2.log ]; then
              echo "vpn_tun_http2.log does not exist"
              exit 1
            fi

            timeout 10s gzip -f vpn_tun_http2.log
            if [ $? -eq 124 ]; then
              truncate -s 300M vpn_tun_http2.log
              timeout 10s gzip -f vpn_tun_http2.log || true
            fi

            popd
        description: Gzip logs
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash

            pushd output
            rm -f vpn_tun_http2.log
            popd
        description: Cleanup
  requirements:
    - adg-privileged-docker
  artifacts:
    - name: Vpn-Libs Log
      location: output
      pattern: '*.gz'
      shared: false
    - name: Test result
      location: output
      pattern: 'output*.json'
      shared: true
repositories:
  - core-libs/vpn-libs:
      scope: global
  - core-libs/vpn-libs-endpoint:
      scope: global
triggers:
  - cron:
      expression: 0 0 9 ? * *
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications:
  - events:
      - plan-failed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-libs
  - events:
      - plan-completed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-libs-vcs
labels: [ ]
other:
  concurrent-build-plugin: system-default
