---
version: 2

plan:
  project-key: CL
  key: VLRT
  name: VpnLibs - Run Tests

stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Run tests on Linux
        - Run tests on Windows
        - Run tests on macOS

Run tests on Linux:
  key: RTL
  docker:
    image: adguard/core-libs:2.6
    volumes:
      ${bamboo.working.directory}: ${bamboo.working.directory}
      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
    docker-run-arguments: [ ]
  tasks:
    - !include docker-clean.yaml
    - checkout:
        force-clean-build: 'true'
        repository: core-libs/vpn-libs
        path: vpn-libs
        description: Checkout Default Repository
    - script:
        - |-
          set -x -e
          ! grep -rnE "SSL(_CTX)?_new" | grep -v "net/src/utils.cpp"
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x -e

            python3 -m pip install conan --upgrade

            conan remote add --index 0 art ${bamboo.conanRepoUrl} || true

            export VL_ROOT=${PWD}
            trap "git clean -d -x -f ${VL_ROOT} --exclude '**/Testing/*/*.xml'" EXIT

            mkdir -p build
            cd build

            cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_C_FLAGS='-fsanitize=address' \
            -DCMAKE_CXX_FLAGS='-fsanitize=address -stdlib=libc++' \
            -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address ${LDFLAGS}" \
            -GNinja \
            ..

            ninja tests && ctest -D ExperimentalTest --no-compress-output
        description: Compile and run tests
        working-dir: vpn-libs
  final-tasks:
    - any-task:
        plugin-key: fr.cstb.bamboo.plugins.ctest.bamboo-ctest-plugin:test
        configuration:
          testFilePathPattern: '**/Testing/*/*.xml'
    - script:
        file: vpn-libs/bamboo-specs/scripts/conan_upload_and_cleanup.sh
        description: Conan upload and cleanup
  requirements:
    - adg-privileged-docker
  artifact-subscriptions: [ ]

Run tests on Windows:
  key: RTW
  tasks:
    - checkout:
        description: Checkout Default Repository
        force-clean-build: 'true'
    - script:
        interpreter: WINDOWS_POWER_SHELL
        scripts:
        - |-
          $ErrorActionPreference = 'Stop'

          & conan remote add --index 0 art ${bamboo.conanRepoUrl}
          $Env:bamboo_sshSecretKey -replace '\\n', "`n" | sc $Env:USERPROFILE\.ssh\id_rsa

          # Save vcvars to switch between them
          $vcvars32 = cmd /c "vcvarsamd64_x86 & set"
          $vcvars64 = cmd /c "vcvars64 & set"
          $vcvarsarm64 = cmd /c "vcvarsamd64_arm64 & set"
          function setvar($_) {
            if ($_ -match "=") {
              $v = $_.split("="); set-item -force -path "ENV:\$($v[0])"  -value "$($v[1])"
            }
          }

          & {
            $vcvars64 | foreach { setvar $_ }
            mkdir build64
            pushd build64
            & cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo `
              -DCMAKE_C_COMPILER="cl.exe" `
              -DCMAKE_CXX_COMPILER="cl.exe" `
              -G Ninja ..
            if (!$?) { exit 1 }
            & ninja vpnlibs_core
            if (!$?) { exit 1 }
            popd
          }
          & {
            $vcvars32 | foreach { setvar $_ }
            mkdir build32
            pushd build32
            & cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo `
              -DCMAKE_C_COMPILER="cl.exe" `
              -DCMAKE_CXX_COMPILER="cl.exe" `
              -G Ninja ..
            if (!$?) { exit 1 }
            & ninja tests
            if (!$?) { exit 1 }
            & ctest -D ExperimentalTest --no-compress-output
            if (!$?) { exit 1 }
            popd
          }
  final-tasks:
    - any-task:
        plugin-key: fr.cstb.bamboo.plugins.ctest.bamboo-ctest-plugin:test
        configuration:
          testFilePathPattern: '**/Testing/*/*.xml'
        description: Parse tests result
    - script:
        interpreter: WINDOWS_POWER_SHELL
        scripts:
          - |-
            conan remote login art $Env:bamboo_artifactoryUser --password $Env:bamboo_artifactoryPassword
            conan upload -r art -c "*" 2>&1 | Select-String "Uploading" -SimpleMatch
            Write-Host "conan upload finished with status $LASTEXITCODE"
            conan remove -c "*" *> $null
            conan cache clean *> $null
        description: Conan upload and cleanup
  requirements:
    - ephemeral-windows
    - image: registry.int.agrd.dev/windows/windows11-bamboo:19
  artifact-subscriptions: [ ]

Run tests on macOS:
  key: RTM
  tasks:
    - checkout:
        description: Checkout Default Repository
        force-clean-build: 'true'
    - script:
        description: Build tests
        interpreter: SHELL
        scripts:
          - |-
            set -e -x

            rm -rf venv
            python3 -m venv venv
            source ./venv/bin/activate
            python3 -m pip install conan

            # Clean up local cache
            conan remove -c "*"

            conan remote add --index 0 art ${bamboo.conanRepoUrl} || true
            VPN_LIBS_ROOT=$(pwd)
            ARCH=$(uname -m)

            # Build tests
            mkdir -p build
            cd build
            cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -GNinja \
                -DTARGET_OS=macos \
                -DCMAKE_C_COMPILER=clang \
                -DCMAKE_CXX_COMPILER=clang++ \
                -DCMAKE_CXX_FLAGS="-fsanitize=address -stdlib=libc++" \
                -DCMAKE_C_FLAGS="-fsanitize=address" \
                -DCMAKE_EXE_LINKER_FLAGS='-fsanitize=address' \
                -DCMAKE_OSX_ARCHITECTURES="$ARCH" \
                ..

            # Needed to avoid a sanitizer error (likely to be false positive)
            # inside gtest
            export ASAN_OPTIONS=detect_container_overflow=0
            ninja tests
            ctest -D ExperimentalTest --no-compress-output
  final-tasks:
    - any-task:
        plugin-key: fr.cstb.bamboo.plugins.ctest.bamboo-ctest-plugin:test
        configuration:
          testFilePathPattern: '**/Testing/*/*.xml'
        description: Parse tests result
    - script:
        interpreter: SHELL
        scripts:
          - |-
            source ./venv/bin/activate
            ./bamboo-specs/scripts/conan_upload_and_cleanup.sh
  requirements:
    - ephemeral
    - image: registry.int.agrd.dev/macos/sequoia-build-agent-xcode26.1.1:latest
  artifact-subscriptions: [ ]

repositories:
  - core-libs/vpn-libs:
      scope: global

branches:
  create: for-pull-request
  delete:
    after-deleted-days: 4
    after-inactive-days: 30
  integration:
    push-on-success: false
    merge-from: VpnLibs - Run tests
  link-to-jira: true

notifications: [ ]

labels: [ ]

other:
  concurrent-build-plugin: system-default
