---
version: 2
plan:
  project-key: CL
  key: VLRIT
  name: VpnLibs - Run Instrumented Test
stages:
  - Default Stage:
      manual: false
      final: false
      jobs:
        - Run Instrumented test
Run Instrumented test:
  key: JOB1
  description: Runs Instrumented tests
  tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash

            set -x -e

            exec docker run --rm --volume ${bamboo.working.directory}:${bamboo.working.directory} adguard/core-libs:1.16 /bin/sh -c 'rm -rf ${bamboo.working.directory}/*'
        description: Clean working directory with root privileges
    - checkout:
        repository: core-libs/vpn-libs
        path: test/client/vpn-libs
        force-clean-build: 'true'
        description: Checkout client
    - checkout:
        repository: core-libs/vpn-libs
        path: test/network-load-simulator/vpn-libs
        force-clean-build: 'true'
        description: Checkout client into "network-load-simulator"
    - checkout:
        repository: core-libs/vpn-libs-endpoint
        path: test/endpoint/vpn-libs-endpoint
        force-clean-build: 'true'
        description: Checkout endpoint
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash

            set -x -e

            cp -RT client/vpn-libs/integration-tests/ ./

            ./integration_test.sh clean
            ./integration_test.sh run browser ${bamboo.conanRepoUrl} ${bamboo.vpnLibsAppId} \
            ${bamboo.vpnLibsTokenSecret} ${bamboo.adguardApiCredPath} \
            ${bamboo.adguardApiVpnLocationPath} ${bamboo.adguardApiDomain} \
            ${bamboo.adguardVpnRelayIp}; exit $?
        description: Run browser tests
        working-dir: test
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash

            set -x

            pushd logs
            # Check that file exists and is not empty
            if [ ! -f vpn_tun_http2.log ]; then
              echo "vpn_tun_http2.log does not exist"
              exit 1
            fi
            
            timeout 10s gzip -f vpn_tun_http2.log
            if [ $? -eq 124 ]; then
              truncate -s 300M vpn_tun_http2.log
              timeout 10s gzip -f vpn_tun_http2.log || true
            fi
            popd

            ./integration_test.sh clean
            ./integration_test.sh clean-browser
        description: Gzip logs
        working-dir: test
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash

            set -x -e

            pushd logs
            rm -f vpn_tun_http2.log
            popd
        description: Cleanup
        working-dir: test
  requirements:
    - adg-privileged-docker
  artifacts:
    -
      name: Vpn-Libs Log
      location: test/logs
      pattern: '*.gz'
      shared: false
    -
      name: Test result
      location: test/
      pattern: 'output*.json'
      shared: true
  artifact-subscriptions: [ ]
repositories:
  - core-libs/vpn-libs:
      scope: global
  - core-libs/vpn-libs-endpoint:
      scope: global
triggers:
  - cron:
      expression: 0 0 9 ? * *
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications:
  - events:
      - plan-failed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-libs
  - events:
      - plan-completed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-libs-vcs
labels: [ ]
other:
  concurrent-build-plugin: system-default
