---
version: 2
plan:
  project-key: CL
  key: VLIT
  name: VpnLibs - Run Integration Test
stages:
  - Build stage:
      manual: false
      final: false
      jobs:
        - Build binaries
  - Tests stage:
      manual: false
      final: false
      jobs:
        - Run integration test
        - Run live test
Build binaries:
  key: BB
  description: Build client and endpoint binaries
  docker:
    image: adguard/core-libs:2.6
  tasks:
    - !include docker-clean.yaml
    - checkout:
        repository: core-libs/vpn-libs
        path: vpn-libs
        force-clean-build: 'true'
        description: Checkout client
    - checkout:
        repository: core-libs/vpn-libs-endpoint
        path: vpn-libs-endpoint
        force-clean-build: 'true'
        description: Checkout endpoint
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash

            set -x -e

            pwd
            ls -l
            mkdir -p output
            export OUTPUT_DIR=${PWD}/output
            export SOURCE_DIR=${PWD}

            export CONAN_REPO_URL=${bamboo.conanRepoUrl}
            vpn-libs/integration-tests/build_client.sh
            vpn-libs/integration-tests/build_endpoint.sh
  requirements:
    - adg-privileged-docker
  artifacts:
    - name: standalone_client
      location: output
      pattern: standalone_client
      shared: true
    - name: vpn_endpoint
      location: output
      pattern: vpn_endpoint
      shared: true
  artifact-subscriptions: [ ]
Run integration test:
  key: JOB1
  description: Runs integration tests
  docker:
    image: adguard/core-libs-testing:2.6.0
    docker-run-arguments: [ --privileged, --device=/dev/net/tun ]
  artifact-subscriptions:
    - artifact: standalone_client
      destination: output
    - artifact: vpn_endpoint
      destination: output
  tasks:
    - !include docker-clean.yaml
    - checkout:
        repository: core-libs/vpn-libs
        path: vpn-libs
        force-clean-build: 'true'
        description: Checkout client
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash

            set -x -e

            export OUTPUT_DIR=${PWD}/output
            export TEST_DIR=${PWD}/vpn-libs/integration-tests/tests

            # Nameserver with global routable IP is required here.
            # 94.140.14.140 is AdGuard Unfiltered DNS
            echo nameserver 94.140.14.140 > /etc/resolv.conf

            ${TEST_DIR}/main/run.sh http2 socks
            ${TEST_DIR}/main/run.sh http3 socks
            ${TEST_DIR}/main/run.sh http2 tun
            ${TEST_DIR}/main/run.sh http3 tun
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash

            set -x

            pushd output

            for log_file in vpn_tun_http2.log vpn_tun_http3.log vpn_socks_http2.log vpn_socks_http3.log; do
            timeout 10s gzip -f $log_file
            if [ $? -eq 124 ]; then
              truncate -s 100M $log_file
              timeout 10s gzip -f $log_file || true
            fi
            done

            popd
        description: Gzip logs
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash

            pushd output
            rm -f vpn_tun_http2.log
            rm -f vpn_tun_http3.log
            rm -f vpn_socks_http2.log
            rm -f vpn_socks_http3.log
            popd
        description: Cleanup
  requirements:
    - adg-privileged-docker
  artifacts:
    - name: Vpn-Libs Log
      location: output
      pattern: '*.gz'
      shared: false
Run live test:
  key: JOB2
  description: Runs C++ live tests
  docker:
    image: adguard/core-libs:2.6
    volumes:
      ${bamboo.working.directory}: ${bamboo.working.directory}
      ${bamboo.tmp.directory}: ${bamboo.tmp.directory}
      ${system.HOME}/.ssh: /root/.ssh
    docker-run-arguments: [ ]
  tasks:
    - !include docker-clean.yaml
    - checkout:
        repository: core-libs/vpn-libs
        path: vpn-libs
        force-clean-build: 'true'
        description: Checkout client
    - checkout:
        repository: core-libs/vpn-libs-endpoint
        path: vpn-libs-endpoint
        force-clean-build: 'true'
        description: Checkout endpoint
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x -e

            python3 -m pip install conan --upgrade

            conan remote add --index 0 art ${bamboo.conanRepoUrl} || true
        description: conan remote
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash

            set -x -e

            SRC_ROOT=${PWD}
            mkdir -p /build_no_asan && cd /build_no_asan

            # Using DNS proxy in VPN libs leads to false-positive address sanitizer errors
            export LDFLAGS=-fuse-ld=lld
            cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_CXX_FLAGS='-stdlib=libc++ -DI_DO_WANT_TO_RUN_LIVE_TESTS' \
            ${SRC_ROOT}

            make -j 4 test_vpn_client_live
        description: Build vpn-libs without address sanitizer
        working-dir: vpn-libs
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash

            set -x -e

            ENDPOINT_HOSTNAME="localhost"

            cargo run --config net.git-fetch-with-cli=true --release --bin setup_wizard -- --mode non-interactive  \
              --address "0.0.0.0:4433" \
              --creds premium:premium  \
              --hostname "$ENDPOINT_HOSTNAME"  \
              --lib-settings vpn.toml  \
              --hosts-settings tls_hosts.toml

            cargo build --config net.git-fetch-with-cli=true --release --bin vpn_endpoint
        description: Build vpn-libs-endpoint
        working-dir: vpn-libs-endpoint
    - script:
        interpreter: SHELL
        description: Run live test
        scripts:
          - |-
            #!/bin/bash

            set -x -e

            export SRC_ROOT=${PWD}

            cd vpn-libs-endpoint
            ./target/release/vpn_endpoint vpn.toml tls_hosts.toml > /dev/null 2>&1 &
            echo "Start endpoint"
            sleep 3

            /build_no_asan/core/test_vpn_client_live
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash
            conan remote login art "${bamboo_artifactoryUser}" --password "${bamboo_artifactoryPassword}" > upload.txt 2>&1
            conan upload -r art -c "*" >> upload.txt 2>&1
            echo conan upload finished with status $?
            conan remove -c "*"
        description: Conan upload and cleanup
  requirements:
    - adg-privileged-docker
  artifact-subscriptions: [ ]
repositories:
  - core-libs/vpn-libs:
      scope: global
  - core-libs/vpn-libs-endpoint:
      scope: global
branches:
  create: for-pull-request
  delete:
    after-deleted-days: 4
    after-inactive-days: 30
  integration:
    push-on-success: false
    merge-from: VpnLibs - Run tests
  link-to-jira: true
notifications: [ ]
labels: [ ]
other:
  concurrent-build-plugin: system-default
