# syntax=docker/dockerfile:1
FROM common-test-image

ARG ENDPOINT_DIR="vpn-libs-endpoint"
ARG ENDPOINT_HOSTNAME="endpoint.test"
ARG CONFIG_FILE="vpn.conf"
ARG TLS_HOSTS_SETTINGS_FILE="tls_hosts.conf"
ARG LOG_LEVEL="info"

VOLUME ${HOME}/.cargo:/root/.cargo

RUN apt install -y openssl

COPY $ENDPOINT_DIR /test/$ENDPOINT_DIR

WORKDIR /test/
RUN cd "$ENDPOINT_DIR" && \
    cargo build --config net.git-fetch-with-cli=true --release --bin vpn_endpoint && \
    mv ./target/release/vpn_endpoint /test/ && \
    openssl req -new -x509 -sha256 -newkey rsa:2048 -nodes -days 1000 \
        -keyout /test/key.pem -out /test/cert.pem \
        -subj "/C=de/CN=$ENDPOINT_HOSTNAME" \
        -addext "subjectAltName = DNS:$ENDPOINT_HOSTNAME, DNS:*.$ENDPOINT_HOSTNAME"

RUN echo "\
listen_address = \"[::]:4433\"\n\
allow_private_network_connections = true\n\
[listen_protocols.http1]\n\
[listen_protocols.http2]\n\
[listen_protocols.quic]\n\
[icmp]\n\
interface_name = \"eth0\"\n\
" >>$CONFIG_FILE

RUN echo "\
[[main_hosts]]\n\
hostname = \"$ENDPOINT_HOSTNAME\"\n\
cert_chain_path = \"cert.pem\"\n\
private_key_path = \"key.pem\"\n\
" >>$TLS_HOSTS_SETTINGS_FILE

ENV LOG_LEVEL=$LOG_LEVEL \
    CONFIG_FILE=$CONFIG_FILE \
    TLS_HOSTS_SETTINGS_FILE=$TLS_HOSTS_SETTINGS_FILE \
    RUST_BACKTRACE=1
ENTRYPOINT ./vpn_endpoint -l "$LOG_LEVEL" "$CONFIG_FILE" "$TLS_HOSTS_SETTINGS_FILE" >> /tmp/vpn.log 2>&1
