name: Run live unit tests

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run-live-unit-tests:
    name: Run live unit tests
    if: github.repository == 'AdGuardSoftwareLimited/trusttunnel-client'
    runs-on:
      - ephemeral
      - ephemeral-linux
      - ${{ vars.BUILD_IMAGE_VERSION_CORELIBS_BUILDER }}
      - ephemeral-limit-memory-8192
      - ephemeral-limit-cpu-6
    container:
      image: adguard/core-libs:2.10
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Build and run live unit tests
        env:
          CONAN_REPO_URL: ${{ vars.CONAN_REPO_URL }}
        run: |
          set -x -e

          python3 -m pip install conan --upgrade
          conan remote add --index 0 art ${CONAN_REPO_URL} || true

          export LDFLAGS=-fuse-ld=lld
          mkdir -p /build_no_asan && cd /build_no_asan
          cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DVPNLIBS_ENABLE_LIVE_TESTS=ON \
            -DCMAKE_CXX_FLAGS='-stdlib=libc++' \
            ${GITHUB_WORKSPACE}

          make -j 4 live_tests
          ctest --output-on-failure -L live -E test_vpn_client_live

      - name: Upload to Conan and cleanup
        if: always()
        run: |
          conan remote login art "${{ secrets.ARTIFACTORY_USER }}" --password "${{ secrets.ARTIFACTORY_API_KEY }}" || true
          conan upload -r art -c "*" 2>&1 | grep "Uploading" || true
          echo "conan upload finished"
          conan remove -c "*" || true
          conan cache clean || true
